version: '3'

services:
  webserver:
    build: .
    command: ["bash", "-c", "airflow db init && airflow users  create --role Admin --username admin --email admin --firstname admin --lastname admin --password admin && airflow webserver"]
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=n

  scheduler:
    build: .
    command: ["bash", "-c", "airflow scheduler"]
    environment:
      - LOAD_EX=n
      
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
