version: '3'

services:
  webserver:
    build: .
    command: ["bash", "-c", "airflow db init && airflow webserver"]
    ports:
      - "8080:8080"
    environment:
      - LOAD_EX=n
      - AIRFLOW_ADMIN_USERNAME=admin
      -


  scheduler:
    build: .
    command: ["bash", "-c", "airflow scheduler"]
    environment:
      - LOAD_EX=n

  flower:
    image: apache/airflow:2.3.3
    command: ["flower"]
    ports:
      - "5555:5555"

  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
