version: 2.1

orbs:
 python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements_data-pipeline.txt 
      - run:
          name: Run tests
          command: pytest

  deploy-to-render:
    machine: # executor type
      image: ubuntu-2004:202010-01 # # recommended linux image - includes Ubuntu 20.04, docker 19.03.13, docker-compose 1.27.4
    steps:
      - run:
          name: Run Curl Command
          command: curl -X GET $RENDER_API_KEY

workflows:
  test-and-deploy:
    jobs:
      - build-and-test
      - deploy-to-render:
          requires:
            - build-and-test
          filters:
            branches:
              only: production