version: 2.1

orbs:
 python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements_data-pipeline.txt 
      - run:
          name: Run tests
          command: pytest

  deploy-to-render:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          app-dir: ./web_api
          pip-dependency-file: requirements_web-api.txt
      - run:
          name: Deploy Model on Render
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> /home/circleci/.profile
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            sudo apt-get install build-essential
            brew upgrade
            brew install deno
            echo 'export PATH="/home/circleci/.deno/bin:$PATH"' >> ~/.bashrc
            brew tap render-oss/render
            brew install render
            render authenticate $RENDER_API_KEY
            render up --path ./web_api/app.py
      # - run:
      #     name: Install Render CLI
      #     command: |
      #       brew upgrade
      #       brew tap render-oss/render
      #       brew install render
      # - run:
      #     name: Deploy to Render
      #     command: |
      #       render authenticate $RENDER_API_KEY
      #       render up --path ./web_api/app.py

workflows:
  test-and-deploy:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main
      - deploy-to-render