version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements_data-pipeline.txt 
      - run:
          name: Run tests
          command: pytest

  deploy-to-render:
    machine:
      image: cimg/python:3.9.5
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Install Homebrew
          command: |
            /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
            (echo; echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"') >> $HOME/.profile
      - run:
          name: Install Deno
          command: |
            curl -fsSL https://deno.land/x/install/install.sh | sh
            export DENO_INSTALL="/root/.deno"
            export PATH="$DENO_INSTALL/bin:$PATH"
      - run:
          name: Install Render CLI
          command: |
            eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
            brew tap render-oss/render
            brew install render
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements_data-pipeline.txt
      - run:
          name: Deploy to Render
          command: |
            render authenticate $RENDER_API_KEY
            render up --path /web_api/app.py

workflows:
  sample:
    jobs:
      - build-and-test
      - deploy-to-render:
          requires:
            - build-and-test
          filters:
            branches:
              only: production
