version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.5
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements_data-pipeline.txt 
      - run:
          name: Run tests
          command: pytest

  deploy-to-render:
    docker:
      - image: homebrew/brew
    steps:
      - attach_workspace:
          at: /root/.cache/pip
      - run:
          name: Install Python 3.9.5
          command: |
            brew install python@3.9.5
      - run:
          name: Install Deno
          command: |
            if ! command -v deno &> /dev/null; then
              curl -fsSL https://deno.land/x/install/install.sh | sh
              export DENO_INSTALL="/root/.deno"
              export PATH="$DENO_INSTALL/bin:$PATH"
            fi
      - run:
          name: Install Render CLI
          command: |
            if ! command -v render &> /dev/null; then
              brew upgrade
              brew tap render-oss/render
              brew install render
            fi
      - run:
          name: Deploy to Render
          command: |
            render authenticate $RENDER_API_KEY
            render up --path /web_api/app.py

workflows:
  sample:
    jobs:
      - build-and-test:
          filters:
            branches:
              only: main
      - deploy-to-render:
          requires:
            - build-and-test
